<?php
/**
 * @file
 * Code for the CiviCRM Case Study feature.
 */

include_once("civicrm_stats.extensions.inc");

/*
function civicrm_stats_install(){
	civicrm_stats_extensions_install();
}

function civicrm_stats_uninstall(){
	civicrm_stats_extensions_uninstall();
}
*/

function civicrm_stats_cron(){
	civicrm_stats_extensions_cron();
}


/**
* Implements hook_block_info().
*/
function civicrm_stats_block_info() {
  $blocks['civicrm_stats'] = array(
    'info' => t('Civicrm stats'),
  );
  return $blocks;
}

/**
* Implements hook_block_view().
*/
function civicrm_stats_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'civicrm_stats':
      $block['content'] = 'getFormattedData(){ //Here goes the code to expose to the frontend  }';
      break;
  }

  return $block;
}


